apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: myfirstdockernode
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: myfirstdockernode
    spec:
      containers:
      - name: myfirstdockernode
        image: plcon.azurecr.io/pleungms/myfirstdockernode:$BUILD_ID
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: myfirstdockernode
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: myfirstdockernode